# dashboard.py

import os
import queue
import re
import subprocess
import sys
import threading
import time
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st
import yaml


# ============================================================
# PROJECT / ENVIRONMENT CONFIGURATION
# ============================================================

ROOT = Path(__file__).resolve().parent

ORCHESTRATOR = ROOT / "orchestrator" / "pipeline_orchestrator.py"
CONFIG_FILE = ROOT / "config" / "config.yaml"
OUTPUT_MR = ROOT / "output_mr"

DEFAULT_INPUT = ROOT / "data" / "original" / "NASA_access_log_full.log"

# Hadoop environment used in your Codespace
HADOOP_HOME = "/usr/local/hadoop"
JAVA_HOME = "/usr/local/sdkman/candidates/java/11.0.32-tem"

os.environ["JAVA_HOME"] = JAVA_HOME
os.environ["HADOOP_HOME"] = HADOOP_HOME
os.environ["HADOOP_CONF_DIR"] = f"{HADOOP_HOME}/etc/hadoop"
os.environ["HADOOP_MAPRED_HOME"] = HADOOP_HOME
os.environ["HADOOP_COMMON_HOME"] = HADOOP_HOME
os.environ["HADOOP_HDFS_HOME"] = HADOOP_HOME
os.environ["YARN_HOME"] = HADOOP_HOME

# Hadoop in your Codespace uses SSH port 2222
os.environ["PDSH_RCMD_TYPE"] = "ssh"
os.environ["PDSH_SSH_ARGS"] = "-p 2222"

os.environ["PATH"] = (
    f"{HADOOP_HOME}/bin:"
    f"{HADOOP_HOME}/sbin:"
    f"{JAVA_HOME}/bin:"
    + os.environ.get("PATH", "")
)


# ============================================================
# STREAMLIT PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="NASA Web Log Analytics",
    page_icon="🚀",
    layout="wide",
)


# ============================================================
# CONFIG HELPERS
# ============================================================

def load_reducer_config():
    defaults = {
        "q1": 1,
        "q2": 1,
        "q3": 1,
    }

    if not CONFIG_FILE.exists():
        return defaults

    try:
        with CONFIG_FILE.open("r") as f:
            cfg = yaml.safe_load(f) or {}

        hadoop_cfg = cfg.get("hadoop", {})

        return {
            "q1": int(hadoop_cfg.get("num_reducers_q1", 1)),
            "q2": int(hadoop_cfg.get("num_reducers_q2", 1)),
            "q3": int(hadoop_cfg.get("num_reducers_q3", 1)),
        }

    except Exception:
        return defaults


# ============================================================
# PARSING HELPERS
# ============================================================

def parse_time(line):
    match = re.search(r"Time:\s*([\d.]+)s", line)
    return float(match.group(1)) if match else None


def parse_total_time(line):
    match = re.search(
        r"COMPLETED SUCCESSFULLY IN\s*([\d.]+)s",
        line,
    )
    return float(match.group(1)) if match else None


def parse_int(line, pattern):
    match = re.search(pattern, line)
    if not match:
        return None

    try:
        return int(match.group(1).replace(",", ""))
    except (ValueError, TypeError):
        return None


# ============================================================
# MAPREDUCE OUTPUT HELPERS
# ============================================================

def output_directory(job):
    mapping = {
        "Q1": "q1_daily_traffic",
        "Q2": "q2_top_resources",
        "Q3": "q3_hourly_errors",
    }

    return OUTPUT_MR / mapping[job]


def read_job_output(job, top_n):
    """
    Read ALL part-* files generated by the MapReduce job.

    Important for Q1/Q3 when multiple reducers are used.
    """

    folder = output_directory(job)

    if not folder.exists():
        return None

    part_files = sorted(
        path
        for path in folder.glob("part-*")
        if path.is_file()
    )

    if not part_files:
        return None

    frames = []

    for path in part_files:
        try:
            df = pd.read_csv(
                path,
                sep="\t",
                header=None,
                engine="python",
            )

            if not df.empty:
                frames.append(df)

        except Exception as exc:
            st.warning(
                f"Could not read {path.name}: {exc}"
            )

    if not frames:
        return None

    df = pd.concat(
        frames,
        ignore_index=True,
    )

    # --------------------------------------------------------
    # Q1
    # --------------------------------------------------------

    if job == "Q1":

        if len(df.columns) == 3:
            df.columns = [
                "Date",
                "Requests",
                "Bytes",
            ]

        df["Date"] = pd.to_datetime(
            df["Date"],
            errors="coerce",
        )

        df["Requests"] = pd.to_numeric(
            df["Requests"],
            errors="coerce",
        )

        df["Bytes"] = pd.to_numeric(
            df["Bytes"],
            errors="coerce",
        )

        df = (
            df.dropna(subset=["Date"])
            .sort_values("Date")
            .reset_index(drop=True)
        )

    # --------------------------------------------------------
    # Q2
    # --------------------------------------------------------

    elif job == "Q2":

        if len(df.columns) == 4:
            df.columns = [
                "Resource",
                "Requests",
                "Bytes",
                "Distinct Hosts",
            ]

        elif len(df.columns) == 3:
            df.columns = [
                "Resource",
                "Requests",
                "Bytes",
            ]

        df["Requests"] = pd.to_numeric(
            df["Requests"],
            errors="coerce",
        )

        df["Bytes"] = pd.to_numeric(
            df["Bytes"],
            errors="coerce",
        )

        df = (
            df.dropna(subset=["Resource", "Requests"])
            .sort_values(
                "Requests",
                ascending=False,
            )
            .head(top_n)
            .reset_index(drop=True)
        )

        df.insert(
            0,
            "Rank",
            range(1, len(df) + 1),
        )

    # --------------------------------------------------------
    # Q3
    # --------------------------------------------------------

    elif job == "Q3":

        if len(df.columns) == 5:
            df.columns = [
                "Hour",
                "Total Requests",
                "Error Requests",
                "Error Rate %",
                "Distinct Error Hosts",
            ]

        elif len(df.columns) == 4:
            df.columns = [
                "Hour",
                "Total Requests",
                "Error Requests",
                "Error Rate %",
            ]

        df["Hour"] = pd.to_datetime(
            df["Hour"],
            errors="coerce",
        )

        for col in [
            "Total Requests",
            "Error Requests",
            "Error Rate %",
        ]:
            df[col] = pd.to_numeric(
                df[col],
                errors="coerce",
            )

        df = (
            df.dropna(subset=["Hour"])
            .sort_values("Hour")
            .reset_index(drop=True)
        )

    return df


# ============================================================
# RESULT RENDERERS
# ============================================================

def render_q1(df):
    st.markdown("## 📊 Q1 — Daily Traffic")

    if df is None or df.empty:
        st.warning("Q1 completed but produced no rows.")
        return

    total_requests = int(
        df["Requests"].sum()
    )

    total_bytes = int(
        df["Bytes"].sum()
    )

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Days",
        f"{len(df):,}",
    )

    c2.metric(
        "Total Requests",
        f"{total_requests:,}",
    )

    c3.metric(
        "Total Volume",
        f"{total_bytes / (1024 ** 2):,.2f} MB",
    )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True,
    )

    fig = px.line(
        df,
        x="Date",
        y="Requests",
        markers=True,
        title="Daily Request Volume",
    )

    st.plotly_chart(
        fig,
        use_container_width=True,
    )


def render_q2(df):
    st.markdown("## 🔝 Q2 — Top Requested Resources")

    if df is None or df.empty:
        st.warning("Q2 completed but produced no rows.")
        return

    c1, c2 = st.columns(2)

    c1.metric(
        "Resources Returned",
        f"{len(df):,}",
    )

    c2.metric(
        "Top Resource Requests",
        f"{int(df.iloc[0]['Requests']):,}",
    )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True,
    )

    fig = px.bar(
        df,
        x="Requests",
        y="Resource",
        orientation="h",
        title=f"Top {len(df)} Requested Resources",
    )

    fig.update_layout(
        yaxis={
            "categoryorder": "total ascending"
        }
    )

    st.plotly_chart(
        fig,
        use_container_width=True,
    )


def render_q3(df):
    st.markdown("## 🚨 Q3 — Hourly Error Analysis")

    if df is None or df.empty:
        st.warning("Q3 completed but produced no rows.")
        return

    peak_idx = df["Error Rate %"].idxmax()
    peak_row = df.loc[peak_idx]

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Hours",
        f"{len(df):,}",
    )

    c2.metric(
        "Total Errors",
        f"{int(df['Error Requests'].sum()):,}",
    )

    c3.metric(
        "Peak Error Rate",
        f"{peak_row['Error Rate %']:.2f}%",
    )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True,
    )

    fig = px.line(
        df,
        x="Hour",
        y="Error Rate %",
        markers=True,
        title="Hourly Error Rate",
    )

    st.plotly_chart(
        fig,
        use_container_width=True,
    )


# ============================================================
# SUBPROCESS READER
# ============================================================

def read_process_output(process, output_queue):
    try:
        for line in iter(process.stdout.readline, ""):
            if not line:
                break

            output_queue.put(
                ("line", line.rstrip())
            )

    except Exception as exc:
        output_queue.put(
            ("error", str(exc))
        )

    finally:
        output_queue.put(
            ("eof", None)
        )


# ============================================================
# STAGE DISPLAY
# ============================================================

def stage_name(stage):
    names = {
        "stage1": "Stage 1 — Raw Log Ingestion",
        "q1": "Q1 — Daily Traffic Analysis",
        "q2": "Q2 — Top Requested Resources",
        "q3": "Q3 — Hourly Error Analysis",
        "stage3": "Stage 3 — Database Loading",
        "stage4": "Stage 4 — Data Quality Validation",
        "stage5": "Stage 5 — Reporting",
    }

    return names.get(
        stage,
        "Starting pipeline..."
    )


# ============================================================
# HEADER
# ============================================================

st.title("🚀 NASA Web Log Analytics")
st.caption(
    "Live ETL • Hadoop Streaming • MapReduce • Data Quality • Performance"
)


# ============================================================
# SIDEBAR
# ============================================================

reducers = load_reducer_config()

st.sidebar.header("Pipeline Configuration")

mode = st.sidebar.selectbox(
    "Execution Mode",
    ["hadoop", "local"],
    index=0,
)

input_path = st.sidebar.text_input(
    "Input File",
    str(DEFAULT_INPUT),
)

top_n = st.sidebar.number_input(
    "Top N Resources",
    min_value=1,
    max_value=100,
    value=20,
    step=1,
)

st.sidebar.markdown("---")

st.sidebar.markdown("### Reducer Configuration")

st.sidebar.write(
    f"Q1: **{reducers['q1']}** reducers"
)

st.sidebar.write(
    f"Q2: **{reducers['q2']}** reducer"
)

st.sidebar.write(
    f"Q3: **{reducers['q3']}** reducers"
)

st.sidebar.caption(
    "Values are read from config/config.yaml."
)

if reducers["q2"] != 1:
    st.sidebar.warning(
        "Q2 should normally remain at 1 reducer "
        "for the current global Top-N implementation."
    )


# ============================================================
# TOP STATUS
# ============================================================

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "Mode",
    mode.upper(),
)

c2.metric(
    "Q1 Reducers",
    reducers["q1"],
)

c3.metric(
    "Q2 Reducer",
    reducers["q2"],
)

c4.metric(
    "Q3 Reducers",
    reducers["q3"],
)


# ============================================================
# RUN BUTTON
# ============================================================

run_button = st.button(
    "▶ Run Pipeline",
    type="primary",
    use_container_width=True,
)


# ============================================================
# PIPELINE
# ============================================================

if run_button:

    # --------------------------------------------------------
    # Validate input
    # --------------------------------------------------------

    input_file = Path(input_path)

    if not input_file.exists():
        st.error(
            f"Input file not found:\n\n{input_file}"
        )
        st.stop()

    # --------------------------------------------------------
    # Command
    # --------------------------------------------------------

    command = [
        sys.executable,
        "-u",  # IMPORTANT: unbuffered stdout
        str(ORCHESTRATOR),
        "--input",
        str(input_file),
        "--output-dir",
        str(ROOT),
        "--mode",
        mode,
        "--top-n",
        str(top_n),
    ]

    env = os.environ.copy()

    # --------------------------------------------------------
    # Live UI placeholders
    # --------------------------------------------------------

    st.markdown("---")

    status_placeholder = st.empty()
    metric_placeholder = st.empty()
    current_line_placeholder = st.empty()

    # Result containers remain on screen
    q1_container = st.container()
    q2_container = st.container()
    q3_container = st.container()

    dq_container = st.container()
    final_container = st.container()

    # --------------------------------------------------------
    # Start pipeline
    # --------------------------------------------------------

    pipeline_start = time.perf_counter()

    try:
        process = subprocess.Popen(
            command,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            env=env,
        )

    except Exception as exc:
        status_placeholder.error(
            f"❌ Failed to start pipeline: {exc}"
        )
        st.stop()

    # --------------------------------------------------------
    # Background reader
    # --------------------------------------------------------

    output_queue = queue.Queue()

    reader = threading.Thread(
        target=read_process_output,
        args=(process, output_queue),
        daemon=True,
    )

    reader.start()

    # --------------------------------------------------------
    # State
    # --------------------------------------------------------

    all_logs = []

    current_stage = None
    current_stage_start = pipeline_start

    current_job = None

    q1_shown = False
    q2_shown = False
    q3_shown = False

    dq_shown = False
    eof_received = False

    input_records = None
    valid_records = None
    malformed_records = None

    q1_time = None
    q2_time = None
    q3_time = None

    final_reported_time = None

    # --------------------------------------------------------
    # Live loop
    # --------------------------------------------------------

    while True:

        # --------------------------------------------
        # Consume available lines
        # --------------------------------------------

        while True:

            try:
                msg_type, value = (
                    output_queue.get_nowait()
                )

            except queue.Empty:
                break

            if msg_type == "line":

                line = value
                all_logs.append(line)

                # ------------------------------------
                # Detect stages
                # ------------------------------------

                if "STAGE 1:" in line:

                    current_stage = "stage1"
                    current_stage_start = time.perf_counter()

                elif (
                    "Submitting Hadoop Job Q1" in line
                    or "Executing Local Job Q1" in line
                ):

                    current_stage = "q1"
                    current_job = "Q1"
                    current_stage_start = time.perf_counter()

                elif (
                    "Submitting Hadoop Job Q2" in line
                    or "Executing Local Job Q2" in line
                ):

                    current_stage = "q2"
                    current_job = "Q2"
                    current_stage_start = time.perf_counter()

                elif (
                    "Submitting Hadoop Job Q3" in line
                    or "Executing Local Job Q3" in line
                ):

                    current_stage = "q3"
                    current_job = "Q3"
                    current_stage_start = time.perf_counter()

                elif "STAGE 3:" in line:

                    current_stage = "stage3"
                    current_job = None
                    current_stage_start = time.perf_counter()

                elif "STAGE 4:" in line:

                    current_stage = "stage4"
                    current_job = None
                    current_stage_start = time.perf_counter()

                elif "STAGE 5:" in line:

                    current_stage = "stage5"
                    current_job = None
                    current_stage_start = time.perf_counter()

                # ------------------------------------
                # Record counts
                # ------------------------------------

                parsed = parse_int(
                    line,
                    r"Total Ingested Records:\s*([\d,]+)",
                )

                if parsed is not None:
                    input_records = parsed

                parsed = parse_int(
                    line,
                    r"Valid Structured Lines:\s*([\d,]+)",
                )

                if parsed is not None:
                    valid_records = parsed

                parsed = parse_int(
                    line,
                    r"Malformed / Skipped:\s*([\d,]+)",
                )

                if parsed is not None:
                    malformed_records = parsed

                # ------------------------------------
                # Job completion
                # ------------------------------------

                if (
                    "Status: SUCCESS" in line
                    and current_job is not None
                ):

                    elapsed = parse_time(line)

                    if elapsed is not None:

                        if (
                            current_job == "Q1"
                            and not q1_shown
                        ):

                            q1_shown = True
                            q1_time = elapsed

                            with q1_container:

                                st.success(
                                    f"✅ Q1 completed in "
                                    f"{elapsed:.3f}s"
                                )

                                df = read_job_output(
                                    "Q1",
                                    top_n,
                                )

                                if df is not None:
                                    render_q1(df)

                                else:
                                    st.warning(
                                        "Q1 completed but "
                                        "output could not be read."
                                    )

                        elif (
                            current_job == "Q2"
                            and not q2_shown
                        ):

                            q2_shown = True
                            q2_time = elapsed

                            with q2_container:

                                st.success(
                                    f"✅ Q2 completed in "
                                    f"{elapsed:.3f}s"
                                )

                                df = read_job_output(
                                    "Q2",
                                    top_n,
                                )

                                if df is not None:
                                    render_q2(df)

                                else:
                                    st.warning(
                                        "Q2 completed but "
                                        "output could not be read."
                                    )

                        elif (
                            current_job == "Q3"
                            and not q3_shown
                        ):

                            q3_shown = True
                            q3_time = elapsed

                            with q3_container:

                                st.success(
                                    f"✅ Q3 completed in "
                                    f"{elapsed:.3f}s"
                                )

                                df = read_job_output(
                                    "Q3",
                                    top_n,
                                )

                                if df is not None:
                                    render_q3(df)

                                else:
                                    st.warning(
                                        "Q3 completed but "
                                        "output could not be read."
                                    )

                        current_job = None

                # ------------------------------------
                # DQ result
                # ------------------------------------

                if (
                    "OVERALL DATA QUALITY VERDICT:"
                    in line
                    and not dq_shown
                ):

                    dq_shown = True

                    with dq_container:

                        st.markdown(
                            "## ✅ Data Quality"
                        )

                        if "PASSED" in line:

                            st.success(
                                "All 7 data-quality checks passed."
                            )

                        else:

                            st.error(
                                "Data-quality validation failed."
                            )

                # ------------------------------------
                # Final runtime
                # ------------------------------------

                parsed_total = parse_total_time(
                    line
                )

                if parsed_total is not None:
                    final_reported_time = parsed_total

                # ------------------------------------
                # Latest log line
                # ------------------------------------

                current_line_placeholder.code(
                    line,
                    language="text",
                )

            elif msg_type == "error":

                current_line_placeholder.error(
                    value
                )

            elif msg_type == "eof":

                eof_received = True

        # --------------------------------------------
        # Live status
        # --------------------------------------------

        now = time.perf_counter()

        total_elapsed = (
            now - pipeline_start
        )

        current_elapsed = (
            now - current_stage_start
        )

        status_placeholder.info(
            f"🔵 **RUNNING**  |  "
            f"{stage_name(current_stage)}  |  "
            f"Stage elapsed: **{current_elapsed:.1f}s**  |  "
            f"Total elapsed: **{total_elapsed:.1f}s**"
        )

        # --------------------------------------------
        # Live metrics
        # --------------------------------------------

        metric_cols = metric_placeholder.columns(4)

        metric_cols[0].metric(
            "Input Records",
            (
                f"{input_records:,}"
                if input_records is not None
                else "Processing..."
            ),
        )

        metric_cols[1].metric(
            "Valid",
            (
                f"{valid_records:,}"
                if valid_records is not None
                else "Processing..."
            ),
        )

        metric_cols[2].metric(
            "Malformed",
            (
                f"{malformed_records:,}"
                if malformed_records is not None
                else "Processing..."
            ),
        )

        metric_cols[3].metric(
            "Elapsed",
            f"{total_elapsed:.1f}s",
        )

        # --------------------------------------------
        # End condition
        # --------------------------------------------

        if (
            eof_received
            and process.poll() is not None
            and output_queue.empty()
        ):
            break

        time.sleep(0.25)

    # ========================================================
    # PROCESS COMPLETE
    # ========================================================

    return_code = process.wait()

    total_elapsed = (
        time.perf_counter()
        - pipeline_start
    )

    with final_container:

        st.markdown("---")

        st.markdown(
            "## 🏁 Pipeline Status"
        )

        if return_code == 0:

            status_placeholder.success(
                f"🟢 **COMPLETED SUCCESSFULLY**  |  "
                f"Total time: **{total_elapsed:.2f}s**"
            )

        else:

            status_placeholder.error(
                f"🔴 **PIPELINE FAILED**  |  "
                f"Exit code: {return_code}  |  "
                f"Time: **{total_elapsed:.2f}s**"
            )

    # ========================================================
    # FINAL PERFORMANCE SUMMARY
    # ========================================================

    st.markdown(
        "## 📊 Performance Summary"
    )

    perf = st.columns(4)

    perf[0].metric(
        "Q1",
        (
            f"{q1_time:.2f}s"
            if q1_time is not None
            else "-"
        ),
    )

    perf[1].metric(
        "Q2",
        (
            f"{q2_time:.2f}s"
            if q2_time is not None
            else "-"
        ),
    )

    perf[2].metric(
        "Q3",
        (
            f"{q3_time:.2f}s"
            if q3_time is not None
            else "-"
        ),
    )

    perf[3].metric(
        "Full Pipeline",
        (
            f"{final_reported_time:.2f}s"
            if final_reported_time is not None
            else f"{total_elapsed:.2f}s"
        ),
    )

    # --------------------------------------------------------
    # Final timing table
    # --------------------------------------------------------

    timing_rows = []

    if q1_time is not None:
        timing_rows.append(
            {
                "Job": "Q1",
                "Reducers": reducers["q1"],
                "Time (s)": round(q1_time, 3),
            }
        )

    if q2_time is not None:
        timing_rows.append(
            {
                "Job": "Q2",
                "Reducers": reducers["q2"],
                "Time (s)": round(q2_time, 3),
            }
        )

    if q3_time is not None:
        timing_rows.append(
            {
                "Job": "Q3",
                "Reducers": reducers["q3"],
                "Time (s)": round(q3_time, 3),
            }
        )

    if timing_rows:

        timing_df = pd.DataFrame(
            timing_rows
        )

        st.dataframe(
            timing_df,
            use_container_width=True,
            hide_index=True,
        )

        fig = px.bar(
            timing_df,
            x="Job",
            y="Time (s)",
            text="Time (s)",
            title="MapReduce Job Runtime",
        )

        st.plotly_chart(
            fig,
            use_container_width=True,
        )

    # ========================================================
    # FULL LOG
    # ========================================================

    with st.expander("📜 Full Pipeline Log"):

        st.code(
            "\n".join(all_logs),
            language="text",
        )

else:

    st.markdown("---")

    st.info(
        "Configure the pipeline and click **Run Pipeline**. "
        "The current stage and live elapsed time will remain "
        "visible while Hadoop is processing."
    )

    st.markdown(
        """
### Live execution

**Stage 1**
→ ingestion statistics appear

**Q1**
→ RUNNING timer  
→ Q1 table + chart appear immediately when complete

**Q2**
→ RUNNING timer  
→ Q2 table + chart appear immediately when complete

**Q3**
→ RUNNING timer  
→ Q3 table + chart appear immediately when complete

**Data Quality**
→ all 7 checks

**Pipeline Status**
→ final status and total timing
"""
    )